### ISSUE TITLE
build: few tests failed

### ISSUE THREAD

**Issue by vitaly-zdanevich** [windsource/evernote-markdown-sync#1]
com.github.windsource.evernotemarkdownsync.EvernoteMarkdownSyncTest > testSync FAILED
    com.github.windsource.evernotemarkdownsync.git.GitException at EvernoteMarkdownSyncTest.java:26

com.github.windsource.evernotemarkdownsync.git.GitServiceTest > testThisRepoNumberOfObjects FAILED
    com.github.windsource.evernotemarkdownsync.git.GitException at GitServiceTest.java:21

com.github.windsource.evernotemarkdownsync.git.GitServiceTest > testThisRepoDateTime FAILED
    com.github.windsource.evernotemarkdownsync.git.GitException at GitServiceTest.java:30

10 tests completed, 3 failed

**Comment by windsource** [comment]
Which platform do you use? I ran tests with Linux and Mac. I will run tests using Windows soon to investigate problem.

**Comment by windsource** [comment]
Which version of git do you use? Could you run `git --version`?

**Comment by vitaly-zdanevich** [comment]
Xubuntu 14.04.3 i386 with all updates

git version 1.9.1

**Comment by windsource** [comment]
evernote-markdown-sync uses `git ls-tree`which does not exist in Git 1.9.1. Could you try to update to 2.5.0?
